# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build project

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package
    
    - name: Check if tag exists
      id: check_tag
      run: |
        tag_name="${GITHUB_REF#refs/tags/}"
        if git rev-parse "refs/tags/$tag_name" >/dev/null 2>&1; then
          echo "Tag already exists"
          echo "::set-output name=tag_exists::true"
        else
          echo "Tag does not exist"
          echo "::set-output name=tag_exists::false"
        fi
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/ocr-1.0-SNAPSHOT-jar-with-dependencies.jar
        asset_name: ocr-1.0-SNAPSHOT-jar-with-dependencies.jar
        asset_content_type: application/java-archive
